# This is a template `.pre-commit-config.yaml` file for snaps
# This file is managed by bootstack-charms-spec and should not be modified
# within individual snap repos. https://launchpad.net/bootstack-charms-spec

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      # Note(sudeephb): Using `--unsafe` with check-yaml to allow using `!include`.
      # More info about `--unsafe`:
      # https://github.com/pre-commit/pre-commit-hooks/blob/main/README.md?plain=1#L85
      - id: check-yaml
        args: ["--unsafe"]
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        types: [ python ]
