repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        args: ["--unsafe"]
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: tox -e lint
        language: system
        types: [ python ]
