---
name: juju-lint
base: core20
summary: Linter for Juju models to compare deployments with configurable policy
adopt-info: juju-lint
description: |
    Linter for remote or local Juju models.
    Compares remote deployments with configurable policy rules.
    Linting can also be performed on a YAML file representing cloud state.
grade: stable
confinement: classic
apps:
  juju-lint:
    command: bin/juju-lint
    environment:
      PATH: "/snap/juju-lint/current/bin:/snap/juju-lint/current/usr/bin:/bin:/usr/bin:/snap/bin"
      PYTHONPATH: $SNAP/usr/lib/python3.8/site-packages:$SNAP/usr/lib/python3.8/dist-packages:$PYTHONPATH
parts:
  juju-lint:
    plugin: python
    requirements:
      - requirements.txt
    source: .
    source-type: git
    # Classic core20 snaps require staged python.
    python-packages: [pip, setuptools, wheel]
    stage-packages:
      - libpython3-stdlib
      - libpython3.8-minimal
      - libpython3.8-stdlib
      - python3.8-minimal
      - python3-distutils
      - python3-minimal
      - python3-pkg-resources
      - python3-pip
      - python3-setuptools
      - python3-venv
      - python3-wheel
    override-build: |
        snapcraftctl build
        echo "Version: $(python3 setup.py --version)"
        snapcraftctl set-version "$(python3 setup.py --version)"
  juju-lint-contrib:
    after:
      - juju-lint
    plugin: dump
    source: .
    prime:
      - contrib
